name: bigdata-ecommerce

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8

    ports:
      - "127.0.0.1:9870:9870"

    environment:
      CLUSTER_NAME: bigdata-ecommerce
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HDFS_CONF_dfs_replication: "1"
      CORE_CONF_hadoop_proxyuser_root_hosts: "*"
      CORE_CONF_hadoop_proxyuser_root_groups: "*"

    volumes:
      - namenode_data:/hadoop/dfs/name

    networks:
      - bigdata-network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8

    depends_on:
      - namenode

    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HDFS_CONF_dfs_replication: "1"
      SERVICE_PRECONDITION: "namenode:9870"

    volumes:
      - datanode_data:/hadoop/dfs/data

    networks:
      - bigdata-network


  flume:
    build:
      context: .
      dockerfile: flume/Dockerfile

    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy

    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HDFS_CONF_dfs_replication: "1"

    volumes:
      - ./flume/flume.conf:/opt/flume/conf/flume.conf:ro
      - ./flume/acompanhar.sh:/app/flume/acompanhar.sh:ro
      - ./dados:/app/dados:ro

    command:
      - /opt/flume/bin/flume-ng
      - agent
      - --conf
      - /opt/flume/conf
      - --conf-file
      - /opt/flume/conf/flume.conf
      - --name
      - agent
      - -Dflume.root.logger=INFO,console

    networks:
      - bigdata-network

  hbase:
    image: harisekhon/hbase:1.4

    ports:
      - "127.0.0.1:16010:16010"
      - "2181:2181"
      - "9090:9090"

    networks:
      - bigdata-network

  flink-jobmanager:
    build:
      context: .
      dockerfile: flink/Dockerfile
    volumes:
      - ./dados:/app/dados:ro
      - ./flink/jobs:/app/jobs:ro

    command: jobmanager

    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

    ports:
      - "127.0.0.1:8081:8081"

    networks:
      - bigdata-network

  flink-taskmanager:
    build:
      context: .
      dockerfile: flink/Dockerfile

    command: taskmanager

    depends_on:
      - flink-jobmanager

    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2

    volumes:
      - ./dados:/app/dados:ro
      - ./flink/jobs:/app/jobs:ro

    networks:
      - bigdata-network

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0

    volumes:
      - hive_metastore_postgresql_data:/var/lib/postgresql/data

    networks:
      - bigdata-network

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore

    command: /opt/hive/bin/hive --service metastore

    environment:
      HIVE_SITE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore-postgresql/metastore"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName: "org.postgresql.Driver"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName: hive
      HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword: hive
      HIVE_SITE_CONF_hive_metastore_warehouse_dir: hdfs://namenode:9000/user/hive/warehouse
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HDFS_CONF_dfs_replication: "1"

    depends_on:
      - hive-metastore-postgresql
      - namenode
      - datanode

    ports:
      - "9083:9083"

    networks:
      - bigdata-network

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore

    command: /opt/hive/bin/hiveserver2

    environment:
      HIVE_SITE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore-postgresql/metastore"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName: "org.postgresql.Driver"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName: hive
      HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword: hive
      HIVE_SITE_CONF_hive_metastore_uris: thrift://hive-metastore:9083
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HDFS_CONF_dfs_replication: "1"

    depends_on:
      - hive-metastore

    ports:
      - "10000:10000"

    networks:
      - bigdata-network

  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2

    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

    ports:
      - "127.0.0.1:8082:8080"
      - "7077:7077"

    volumes:
      - ./dados:/app/dados:ro
      - ./spark/jobs:/app/jobs:ro
      - ./spark/conf/hive-site.xml:/spark/conf/hive-site.xml:ro

    depends_on:
      - namenode
      - datanode
      - hive-metastore

    networks:
      - bigdata-network

  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2

    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

    depends_on:
      - spark-master

    ports:
      - "127.0.0.1:8083:8081"

    volumes:
      - ./dados:/app/dados:ro
      - ./spark/jobs:/app/jobs:ro
      - ./spark/conf/hive-site.xml:/spark/conf/hive-site.xml:ro

    networks:
      - bigdata-network

volumes:
  namenode_data:
  datanode_data:
  hive_metastore_postgresql_data:

networks:
  bigdata-network:
    driver: bridge