
# Nome dos componentes
agent.sources = source1
agent.channels = channel1
agent.sinks = sink1

# SOURCE: Gerador Python
agent.sources.source1.type = exec
agent.sources.source1.command = sh /app/flume/acompanhar.sh
agent.sources.source1.channels = channel1

# CHANNEL: Armazenamento temporario em memoria
agent.channels.channel1.type = memory
agent.channels.channel1.capacity = 10000
agent.channels.channel1.transactionCapacity = 1000

# SINK: Armazenamento no HDFS
agent.sinks.sink1.type = hdfs
agent.sinks.sink1.hdfs.path = hdfs://namenode:9000/dados/ecommerce
agent.sinks.sink1.hdfs.fileType = DataStream
agent.sinks.sink1.hdfs.writeFormat = Text

# Criar arquivos periodicamente
agent.sinks.sink1.hdfs.rollInterval = 30
agent.sinks.sink1.hdfs.rollSize = 0
agent.sinks.sink1.hdfs.rollCount = 0

# Conectar o sink ao channel
agent.sinks.sink1.channel = channel1
